### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by scaytrase** [bankiru/jsonrpc-server-bundle#1]
- [ ] Travis
- [ ] Insight
- [ ] https://scrutinizer-ci.com/
- [ ] https://coveralls.io/
- [ ] Badges for all above and packagist
